### ISSUE TITLE
Unable to find a device

### ISSUE THREAD

**Issue by nul800sebastiaan** [Duncan-Idaho/LuxaforSharp#1]
I built a super tiny console app and installed the `LuxaforSharp` NuGet package,
Unfortunately, the example code doesn't let me find a device. I tried unplugging it and plugging it back in a few times but I get the same problem each time. Any hints?

```
using System;
using System.Linq;
using LuxaforSharp;

namespace ConsoleApplication1
{
    class Program
    {
        static void Main(string[] args)
        {
            IDeviceList list = new DeviceList();
            IDevice device = list.FirstOrDefault();
            if(device != null)
                device.SetColor(LedTarget.All, new Color(0, 0, 255)); // Immediatly switches all leds to green
            else 
                Console.WriteLine("Device not found :-(");

            Console.ReadKey();
        }
    }
}
```

![image](https://cloud.githubusercontent.com/assets/304656/10642888/3fdb0fe2-7820-11e5-83d7-a8456f3175c9.png)

**Comment by Duncan-Idaho** [comment]
Hello,

You need to call list.Scan() first.

For now, HidLibrary offers no way (at least that I know of) to listen to new devices being plugged in or devices being unplugged. As a result, the only way we can watch for addition or removal of devices is through polling. But I do not wish LuxaforSharp to be directly responsible of the recurring timer of the polling itself. Therefore, on my own project, I have a timer that calls Scan periodically.

If you know any other way of listening to devices, don't hesitate to let me know, or to contribute.

Besides, I prefer to avoid complex operations in constructor, so even if we implement "such observing mode", there would still be a StartListening method.

I hope this will unblock you.

Sincerely,

**Comment by Duncan-Idaho** [comment]
I updated the README.md file.

I'm closing this issue since I believe this will solve your case. If it doesn't work, don't hesitate to reopen it. If you have any other issue, don't hesitate to record new ones.

Thanks!
Sincerely,

**Comment by nul800sebastiaan** [comment]
Sorry for the late reply, I actually tested it immediately after and that worked perfectly, thanks!
